#!/usr/bin/env bash

./node_modules/.bin/nearleyc ./ts/lab3456/verbosetree/grammar.ne -o ./ts/lab3456/verbosetree/grammar.ts
# tsc --target ES5 --outDir build  ts/index.ts
./node_modules/.bin/tsc
./node_modules/.bin/browserify build/index.js -o build/bundle.js
echo Done!
